package com.mpcz.deposit_scheme.backend.api.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.query.Procedure;

import com.mpcz.deposit_scheme.backend.api.domain.ErpStagingData;

public interface ErpStagingDataRepository extends JpaRepository<ErpStagingData, Long>{

	
	@Query(value="SELECT \r\n"
			+ "    'DSP PORTAL' AS \"TRANSACTION_SOURCE\",\r\n"
			+ "    CIR.CIRCLE AS \"OU\",\r\n"
			+ "    CIR.CIRCLE AS \"CIRCLE\",\r\n"
			+ "    DIV.DIVISION AS \"DIVISION\",\r\n"
			+ "    DC.DC_NAME AS \"DC\",\r\n"
			+ "    '' AS \"CLASS\",\r\n"
			+ "    '' AS \"TRANSACTION_TYPE\",\r\n"
			+ "    '' AS \"REF_SALES_NO\",\r\n"
			+ "    TO_DATE(SUBSTR(BPR.TRANSACTION_DATE, 1, 10), 'YYYY-MM-DD') AS \"INVOICE_DATE\",\r\n"
			+ "  -- ✅ Fixed date issue\r\n"
			+ "    NULL AS \"GL_DATE\",  -- ✅ Replaced empty string with NULL\r\n"
			+ "    NVL(BPR.Amount, 0) AS \"AMOUNT\",\r\n"
			+ "    'INR' AS \"CURRENCY\",\r\n"
			+ "    BPR.CONSUMER_NAME AS \"CUSTOMER_NAME\",\r\n"
			+ "    BPR.CONSUMER_APPLICATION_NO AS \"CUST_NUMBER\",		\r\n"
			+ "    '' AS \"PAYMENT_TERM\",\r\n"
			+ "    '' AS \"ITEM_DESCRIPTION\",\r\n"
			+ "    '' AS \"QUANTITY\",	\r\n"
			+ "    '' AS \"UNIT_PRICE\",	\r\n"
			+ "    '' AS \"COM_LEGACY_SYS\",\r\n"
			+ "    '' AS \"GL_ACC_COMBI\",\r\n"
			+ "    '' AS \"TAX_RATE\",\r\n"
			+ "    '' AS \"TAX_CATEGORY\",\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 1000 \r\n"
			+ "            ELSE 0 \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"REG_AMOUNT\",\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 0 \r\n"
			+ "            ELSE B.SUPERVISION_AMOUNT \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"SUPE_CHARGES\",	\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 0 \r\n"
			+ "            ELSE B.KVALOAD \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"SUPP_AFFO_CHARGES\",	\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 0 \r\n"
			+ "            ELSE B.KWLOAD \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"SYS_DEVE_CHARGES\",	\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 0 \r\n"
			+ "            ELSE B.JE_RETURN_AMOUNT \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"JE_RETURN_AMOUNT\",\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 90 \r\n"
			+ "            ELSE B.CGST \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"CGST\",	\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 90 \r\n"
			+ "            ELSE B.SGST \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"SGST\",	\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 0 \r\n"
			+ "            ELSE B.DEPOSIT_AMOUNT \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"DEPOSIT\",	\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 0 \r\n"
			+ "            ELSE C.ABEDAN_SULK \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"AVEDAN_SHULK_62\",	\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 0 \r\n"
			+ "            ELSE C.AVEDAN_SHULK_FIVE_RUPEE \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"AVEDAN_SHULK_47\",	\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 0 \r\n"
			+ "            ELSE C.SECURITY_DEPOSIT \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"SECURITY_DEPOSIT\",\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 0 \r\n"
			+ "            ELSE C.PAYALE_AMOUNT \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"PAID_BY_APPLICANT\",\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 0 \r\n"
			+ "            ELSE B.COLONY_OR_SLUM \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"DEPO_FOR_ELE_ILLEGAL\",\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN 0 \r\n"
			+ "            ELSE B.U_SEC_194J_TDS2 \r\n"
			+ "        END, 0\r\n"
			+ "    ) AS \"TDS\",	\r\n"
			+ "\r\n"
			+ "    NVL(\r\n"
			+ "        CASE \r\n"
			+ "            WHEN BPR.ADDITIONAL_INFO1 = 'Registration_Fees' THEN '0' \r\n"
			+ "            ELSE A.GST_NUMBER \r\n"
			+ "        END, '0'\r\n"
			+ "    ) AS \"GST_NUMBER\",\r\n"
			+ "\r\n"
			+ "    '' AS \"RECEIP_NUM\",\r\n"
			+ "    '' AS \"RECEIP_STATUS\",\r\n"
			+ "    '' AS \"INVOICE_NUM\",\r\n"
			+ "    '' AS \"INVOICE_STATUS\",\r\n"
			+ "    '' AS \"CUSTOMER_NUM\",\r\n"
			+ "    '' AS \"CUSTOMER_STATUS\",\r\n"
			+ "    '' AS \"ERROR_MESSAGE\",\r\n"
			+ "    NULL AS \"CREATED_BY\",  -- ✅ Replaced empty string with NULL\r\n"
			+ "    NULL AS \"CREATION_DATE\",  -- ✅ Fixed date issue\r\n"
			+ "    NULL AS \"LAST_UPDATE_DATE\",  -- ✅ Fixed date issue\r\n"
			+ "    NULL AS \"LAST_UPDATED_BY\",\r\n"
			+ "    NULL AS \"LAST_UPDATE_LOGIN\"\r\n"
			+ "\r\n"
			+ "FROM \r\n"
			+ "    CONSUMER_APPLICATION_DETAIL A\r\n"
			+ "LEFT JOIN \r\n"
			+ "    ERP_BUDGET_WORKFLOW_AMOUNT B ON A.ERP_WORKFLOW_NUMBER = B.ERP_NO\r\n"
			+ "LEFT JOIN \r\n"
			+ "    MKY_PAY_AMNT C ON A.CONSUMER_APPLICATION_NUMBER = C.CON_APP_NUM\r\n"
			+ "LEFT JOIN \r\n"
			+ "    ERP_REV D ON A.CONSUMER_APPLICATION_NUMBER = D.CONS_APP_NO\r\n"
			+ "LEFT JOIN \r\n"
			+ "    BILLDESK_PAYMENT_RES BPR ON A.CONSUMER_APPLICATION_NUMBER = BPR.CONSUMER_APPLICATION_NO\r\n"
			+ "JOIN \r\n"
			+ "    DISTRIBUTION_CENTER DC ON DC.DC_ID = A.DC_ID\r\n"
			+ "JOIN \r\n"
			+ "    SUB_DIVISION SD ON SD.SUBDIV_ID = DC.SUBDIV_ID\r\n"
			+ "JOIN \r\n"
			+ "    DIVISION DIV ON DIV.DIV_ID = SD.DIVISION_ID\r\n"
			+ "JOIN \r\n"
			+ "    CIRCLE CIR ON CIR.CIRCLE_ID = DIV.CIRCLE_ID\r\n"
			+ "JOIN \r\n"
			+ "    REGION REG ON CIR.REGION_ID = REG.REGION_ID\r\n"
			+ "JOIN \r\n"
			+ "    DISCOM DIS ON REG.DISCOM_ID = DIS.DISCOM_ID\r\n"
			+ "\r\n"
			+ "WHERE \r\n"
			+ "    BPR.auth_status = '0300' \r\n"
			+ "    AND rownum < 2", nativeQuery = true)
	List<ErpStagingData> extractDataFromSource();

	
	
	@Procedure(name = "DATA_TO_ERP")
    void callDataToErpProcedure();
}
