
#spring.profiles.active=${ACTIVE_PROFILE}
spring.profiles.active=dev
#port configuration
server.port=8083

# OracleDB connection settings  
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect
server.servlet.context-path=/deposit_scheme
spring.jackson.serialization.fail-on-empty-beans=false


jwt.header=Authorization
jwt.secret =  serviceAmit4321!@#$
jwt.expiration = 30000

spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.connection-timeout=6000
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.idleTimeout=60000
spring.datasource.hikari.poolName=ServicesHikariCP

spring.datasource.hikari.data-source-properties.oracle.jdbc.implicitStatementCacheSize=100
spring.datasource.hikari.data-source-properties.oracle.jdbc.maxStatements=100
spring.jpa.properties.hibernate.criteria.literal_handling_mode=BIND
spring.jpa.properties.hibernate.query.plan_cache_max_size=256
spring.jpa.properties.hibernate.query.plan_parameter_metadata_max_size=128

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false




logging.level.org.springframework.web=DEBUG

#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

maxFileCount = 1000000

upload.path = D://UploadDocsNew
#upload.path = ${uploadPathNew}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#logging.file.name=D:/BilldeskLogFile/log/info.log

logging.file.name=D:/LogFile/log/info.log
logging.file.max-size=200MB
logging.file.max-history=10


# Custom logger for the scheduler
#logging.level.com.mpcz.deposit_scheme.backend.api.controller=DEBUG
#logging.file.name=D:/BilldeskLogFile/scheduler.log

#spring.devtools.restart.enabled=false
spring.datasource.initialization-mode=always


# Set read timeout (in milliseconds)
feign.client.config.oyt-api.readTimeout=600000
feign.client.config.oyt-api.connectTimeout=60000


# ===============================
# NORMAL API RATE LIMITER
# ===============================

resilience4j.ratelimiter.instances.normalApiLimiter.limitForPeriod=5
resilience4j.ratelimiter.instances.normalApiLimiter.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.normalApiLimiter.timeoutDuration=0


# ===============================
# PAYMENT API RATE LIMITER
# ===============================

#resilience4j.ratelimiter.instances.paymentApiLimiter.limitForPeriod=2
#resilience4j.ratelimiter.instances.paymentApiLimiter.limitRefreshPeriod=1m
#resilience4j.ratelimiter.instances.paymentApiLimiter.timeoutDuration=0


# Enable cache
spring.cache.type=redis

# Redis connection
spring.redis.host=localhost
spring.redis.port=6379

# Timeout
spring.redis.timeout=60000


# Feign client timeout configuration
logging.level.feign=DEBUG
feign.client.config.oyt-api-1.connectTimeout=1000000
feign.client.config.oyt-api-1.readTimeout=6000000

# OR for all feign clients
feign.client.config.default.connectTimeout=1000000
feign.client.config.default.readTimeout=6000000

# ===============================
# NORMAL API RATE LIMITER (Keep these as they are for other uses)
# ===============================




#WFMS Implementation
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://172.24.200.227:8080/realms/WFMS-Sync